name: Kernel Build with KernelSU (Clang)

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout source
      uses: actions/checkout@v3

    # Set up build environment
    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y git build-essential bc libncurses5-dev bison flex libssl-dev curl cpio clang

    # Set up cross-compilation tools
    - name: Install GCC Toolchain
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu
        export CROSS_COMPILE=aarch64-linux-gnu-

    # Set up Clang Toolchain
    - name: Install Clang
      run: |
        sudo apt install -y clang
        export CC=clang
        export CROSS_COMPILE=clang-

    # Build the kernel with KernelSU
    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=clang-
        make a22x_defconfig
        make -j$(nproc)

    # Upload artifacts
    - name: Upload built kernel
      uses: actions/upload-artifact@v3
      with:
        name: kernel-build
        path: arch/arm64/boot/Image.gz-dtb
