name: Kernel Build with KernelSU

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout source
      uses: actions/checkout@v3

    # Set up build environment
    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y git build-essential bc libncurses5-dev bison flex libssl-dev curl cpio wget

    # Download and install Clang toolchain (clang-r383902)
    - name: Download and install Clang toolchain
      run: |
        # Download and extract clang-r383902 toolchain
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/3857008389202edac32d57008bb8c99d2c957f9d/clang-r383902.tar.gz
        tar -xvzf clang-r383902.tar.gz -C /usr/local/
        # Set environment variables
        export PATH=/usr/local/clang-r383902/bin:$PATH
        export CC=/usr/local/clang-r383902/bin/clang

    # Set up cross-compilation tools (GCC toolchain)
    - name: Install GCC Toolchain
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu
        export CROSS_COMPILE=aarch64-linux-gnu-

    # Build the kernel with KernelSU
    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make a22x_defconfig
        make -j$(nproc)

    # Upload artifacts
    - name: Upload built kernel
      uses: actions/upload-artifact@v3
      with:
        name: kernel-build
        path: arch/arm64/boot/Image.gz-dtb
