name: Kernel Build with KernelSU

on:
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout source
      uses: actions/checkout@v3

    # Set up build environment
    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y git build-essential bc libncurses5-dev bison flex libssl-dev curl cpio

    # Set up cross-compilation tools
    - name: Download GCC or Clang Toolchain
      run: |
        wget https://mirrors.edge.kernel.org/pub/tools/crosstool/files/bin/x86_64/arm64-linux-gnu-gcc-10.3.tar.gz
        tar -xf arm64-linux-gnu-gcc-10.3.tar.gz
        export PATH=$PWD/arm64-linux-gnu/bin:$PATH

    # Build the kernel with KernelSU
    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make <your_defconfig>
        make -j$(nproc)

    # Upload artifacts
    - name: Upload built kernel
      uses: actions/upload-artifact@v3
      with:
        name: kernel-build
        path: arch/arm64/boot/Image.gz-dtb
