name: Kernel Build with KernelSU

on:
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout source
      uses: actions/checkout@v3

    # Set up build environment
    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y git build-essential bc libncurses5-dev bison flex libssl-dev curl cpio

    # Set up cross-compilation tools
    - name: Download GCC Toolchain
      run: |
        wget https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz
        tar -xf gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz
        export PATH=$PWD/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin:$PATH


 # Build the kernel with KernelSU
 - name: Build Kernel
   run: |
     export ARCH=arm64
     export SUBARCH=arm64
     export CROSS_COMPILE=aarch64-linux-gnu-
     make <a22x_defconfig>
     make -j$(nproc)


    # Upload artifacts
    - name: Upload built kernel
      uses: actions/upload-artifact@v3
      with:
        name: kernel-build
        path: arch/arm64/boot/Image.gz-dtb
